# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""
# Piranha FastJet Contrib

Python interface to the Piranha FastJet contrib package.

"""


import eventgeometry



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _piranha
else:
    import _piranha

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _piranha.SWIG_PyInstanceMethod_New
_swig_new_static_method = _piranha.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _piranha.delete_SwigPyIterator
    value = _swig_new_instance_method(_piranha.SwigPyIterator_value)
    incr = _swig_new_instance_method(_piranha.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_piranha.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_piranha.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_piranha.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_piranha.SwigPyIterator_copy)
    next = _swig_new_instance_method(_piranha.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_piranha.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_piranha.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_piranha.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_piranha.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_piranha.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_piranha.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_piranha.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_piranha.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_piranha.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _piranha:
_piranha.SwigPyIterator_swigregister(SwigPyIterator)

import eventgeometry
import pyfjcore

from eventgeometry import FastJetError

class pairDouble(object):
    r"""Proxy of C++ std::pair< double,double > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(pairDouble self) -> pairDouble
        __init__(pairDouble self, double first, double second) -> pairDouble
        __init__(pairDouble self, pairDouble other) -> pairDouble
        """
        _piranha.pairDouble_swiginit(self, _piranha.new_pairDouble(*args))
    first = property(_piranha.pairDouble_first_get, _piranha.pairDouble_first_set, doc=r"""first : double""")
    second = property(_piranha.pairDouble_second_get, _piranha.pairDouble_second_set, doc=r"""second : double""")
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _piranha.delete_pairDouble

# Register pairDouble in _piranha:
_piranha.pairDouble_swigregister(pairDouble)

class pairPairDouble(object):
    r"""Proxy of C++ std::pair< std::pair< double,double >,std::pair< double,double > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(pairPairDouble self) -> pairPairDouble
        __init__(pairPairDouble self, pairDouble first, pairDouble second) -> pairPairDouble
        __init__(pairPairDouble self, pairPairDouble other) -> pairPairDouble
        """
        _piranha.pairPairDouble_swiginit(self, _piranha.new_pairPairDouble(*args))
    first = property(_piranha.pairPairDouble_first_get, _piranha.pairPairDouble_first_set, doc=r"""first : std::pair<(double,double)>""")
    second = property(_piranha.pairPairDouble_second_get, _piranha.pairPairDouble_second_set, doc=r"""second : std::pair<(double,double)>""")
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _piranha.delete_pairPairDouble

# Register pairPairDouble in _piranha:
_piranha.pairPairDouble_swigregister(pairPairDouble)

class vectorVectorDouble(object):
    r"""Proxy of C++ std::vector< std::vector< double > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_piranha.vectorVectorDouble_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_piranha.vectorVectorDouble___nonzero__)
    __bool__ = _swig_new_instance_method(_piranha.vectorVectorDouble___bool__)
    __len__ = _swig_new_instance_method(_piranha.vectorVectorDouble___len__)
    __getslice__ = _swig_new_instance_method(_piranha.vectorVectorDouble___getslice__)
    __setslice__ = _swig_new_instance_method(_piranha.vectorVectorDouble___setslice__)
    __delslice__ = _swig_new_instance_method(_piranha.vectorVectorDouble___delslice__)
    __delitem__ = _swig_new_instance_method(_piranha.vectorVectorDouble___delitem__)
    __getitem__ = _swig_new_instance_method(_piranha.vectorVectorDouble___getitem__)
    __setitem__ = _swig_new_instance_method(_piranha.vectorVectorDouble___setitem__)
    pop = _swig_new_instance_method(_piranha.vectorVectorDouble_pop)
    append = _swig_new_instance_method(_piranha.vectorVectorDouble_append)
    empty = _swig_new_instance_method(_piranha.vectorVectorDouble_empty)
    size = _swig_new_instance_method(_piranha.vectorVectorDouble_size)
    swap = _swig_new_instance_method(_piranha.vectorVectorDouble_swap)
    begin = _swig_new_instance_method(_piranha.vectorVectorDouble_begin)
    end = _swig_new_instance_method(_piranha.vectorVectorDouble_end)
    rbegin = _swig_new_instance_method(_piranha.vectorVectorDouble_rbegin)
    rend = _swig_new_instance_method(_piranha.vectorVectorDouble_rend)
    clear = _swig_new_instance_method(_piranha.vectorVectorDouble_clear)
    get_allocator = _swig_new_instance_method(_piranha.vectorVectorDouble_get_allocator)
    pop_back = _swig_new_instance_method(_piranha.vectorVectorDouble_pop_back)
    erase = _swig_new_instance_method(_piranha.vectorVectorDouble_erase)

    def __init__(self, *args):
        r"""
        __init__(vectorVectorDouble self) -> vectorVectorDouble
        __init__(vectorVectorDouble self, vectorVectorDouble other) -> vectorVectorDouble
        __init__(vectorVectorDouble self, std::vector< std::vector< double > >::size_type size) -> vectorVectorDouble
        __init__(vectorVectorDouble self, std::vector< std::vector< double > >::size_type size, vectorDouble value) -> vectorVectorDouble
        """
        _piranha.vectorVectorDouble_swiginit(self, _piranha.new_vectorVectorDouble(*args))
    push_back = _swig_new_instance_method(_piranha.vectorVectorDouble_push_back)
    front = _swig_new_instance_method(_piranha.vectorVectorDouble_front)
    back = _swig_new_instance_method(_piranha.vectorVectorDouble_back)
    assign = _swig_new_instance_method(_piranha.vectorVectorDouble_assign)
    resize = _swig_new_instance_method(_piranha.vectorVectorDouble_resize)
    insert = _swig_new_instance_method(_piranha.vectorVectorDouble_insert)
    reserve = _swig_new_instance_method(_piranha.vectorVectorDouble_reserve)
    capacity = _swig_new_instance_method(_piranha.vectorVectorDouble_capacity)
    __swig_destroy__ = _piranha.delete_vectorVectorDouble

# Register vectorVectorDouble in _piranha:
_piranha.vectorVectorDouble_swigregister(vectorVectorDouble)

class vectorSubtractionHistory(object):
    r"""Proxy of C++ std::vector< fastjet::contrib::piranha::SubtractionHistory > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_piranha.vectorSubtractionHistory_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_piranha.vectorSubtractionHistory___nonzero__)
    __bool__ = _swig_new_instance_method(_piranha.vectorSubtractionHistory___bool__)
    __len__ = _swig_new_instance_method(_piranha.vectorSubtractionHistory___len__)
    __getslice__ = _swig_new_instance_method(_piranha.vectorSubtractionHistory___getslice__)
    __setslice__ = _swig_new_instance_method(_piranha.vectorSubtractionHistory___setslice__)
    __delslice__ = _swig_new_instance_method(_piranha.vectorSubtractionHistory___delslice__)
    __delitem__ = _swig_new_instance_method(_piranha.vectorSubtractionHistory___delitem__)
    __getitem__ = _swig_new_instance_method(_piranha.vectorSubtractionHistory___getitem__)
    __setitem__ = _swig_new_instance_method(_piranha.vectorSubtractionHistory___setitem__)
    pop = _swig_new_instance_method(_piranha.vectorSubtractionHistory_pop)
    append = _swig_new_instance_method(_piranha.vectorSubtractionHistory_append)
    empty = _swig_new_instance_method(_piranha.vectorSubtractionHistory_empty)
    size = _swig_new_instance_method(_piranha.vectorSubtractionHistory_size)
    swap = _swig_new_instance_method(_piranha.vectorSubtractionHistory_swap)
    begin = _swig_new_instance_method(_piranha.vectorSubtractionHistory_begin)
    end = _swig_new_instance_method(_piranha.vectorSubtractionHistory_end)
    rbegin = _swig_new_instance_method(_piranha.vectorSubtractionHistory_rbegin)
    rend = _swig_new_instance_method(_piranha.vectorSubtractionHistory_rend)
    clear = _swig_new_instance_method(_piranha.vectorSubtractionHistory_clear)
    get_allocator = _swig_new_instance_method(_piranha.vectorSubtractionHistory_get_allocator)
    pop_back = _swig_new_instance_method(_piranha.vectorSubtractionHistory_pop_back)
    erase = _swig_new_instance_method(_piranha.vectorSubtractionHistory_erase)

    def __init__(self, *args):
        r"""
        __init__(vectorSubtractionHistory self) -> vectorSubtractionHistory
        __init__(vectorSubtractionHistory self, vectorSubtractionHistory other) -> vectorSubtractionHistory
        __init__(vectorSubtractionHistory self, std::vector< fastjet::contrib::piranha::SubtractionHistory >::size_type size) -> vectorSubtractionHistory
        __init__(vectorSubtractionHistory self, std::vector< fastjet::contrib::piranha::SubtractionHistory >::size_type size, SubtractionHistory value) -> vectorSubtractionHistory
        """
        _piranha.vectorSubtractionHistory_swiginit(self, _piranha.new_vectorSubtractionHistory(*args))
    push_back = _swig_new_instance_method(_piranha.vectorSubtractionHistory_push_back)
    front = _swig_new_instance_method(_piranha.vectorSubtractionHistory_front)
    back = _swig_new_instance_method(_piranha.vectorSubtractionHistory_back)
    assign = _swig_new_instance_method(_piranha.vectorSubtractionHistory_assign)
    resize = _swig_new_instance_method(_piranha.vectorSubtractionHistory_resize)
    insert = _swig_new_instance_method(_piranha.vectorSubtractionHistory_insert)
    reserve = _swig_new_instance_method(_piranha.vectorSubtractionHistory_reserve)
    capacity = _swig_new_instance_method(_piranha.vectorSubtractionHistory_capacity)
    __swig_destroy__ = _piranha.delete_vectorSubtractionHistory

# Register vectorSubtractionHistory in _piranha:
_piranha.vectorSubtractionHistory_swigregister(vectorSubtractionHistory)

class vectorPairDouble(object):
    r"""Proxy of C++ std::vector< std::pair< double,double > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_piranha.vectorPairDouble_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_piranha.vectorPairDouble___nonzero__)
    __bool__ = _swig_new_instance_method(_piranha.vectorPairDouble___bool__)
    __len__ = _swig_new_instance_method(_piranha.vectorPairDouble___len__)
    __getslice__ = _swig_new_instance_method(_piranha.vectorPairDouble___getslice__)
    __setslice__ = _swig_new_instance_method(_piranha.vectorPairDouble___setslice__)
    __delslice__ = _swig_new_instance_method(_piranha.vectorPairDouble___delslice__)
    __delitem__ = _swig_new_instance_method(_piranha.vectorPairDouble___delitem__)
    __getitem__ = _swig_new_instance_method(_piranha.vectorPairDouble___getitem__)
    __setitem__ = _swig_new_instance_method(_piranha.vectorPairDouble___setitem__)
    pop = _swig_new_instance_method(_piranha.vectorPairDouble_pop)
    append = _swig_new_instance_method(_piranha.vectorPairDouble_append)
    empty = _swig_new_instance_method(_piranha.vectorPairDouble_empty)
    size = _swig_new_instance_method(_piranha.vectorPairDouble_size)
    swap = _swig_new_instance_method(_piranha.vectorPairDouble_swap)
    begin = _swig_new_instance_method(_piranha.vectorPairDouble_begin)
    end = _swig_new_instance_method(_piranha.vectorPairDouble_end)
    rbegin = _swig_new_instance_method(_piranha.vectorPairDouble_rbegin)
    rend = _swig_new_instance_method(_piranha.vectorPairDouble_rend)
    clear = _swig_new_instance_method(_piranha.vectorPairDouble_clear)
    get_allocator = _swig_new_instance_method(_piranha.vectorPairDouble_get_allocator)
    pop_back = _swig_new_instance_method(_piranha.vectorPairDouble_pop_back)
    erase = _swig_new_instance_method(_piranha.vectorPairDouble_erase)

    def __init__(self, *args):
        r"""
        __init__(vectorPairDouble self) -> vectorPairDouble
        __init__(vectorPairDouble self, vectorPairDouble other) -> vectorPairDouble
        __init__(vectorPairDouble self, std::vector< std::pair< double,double > >::size_type size) -> vectorPairDouble
        __init__(vectorPairDouble self, std::vector< std::pair< double,double > >::size_type size, pairDouble value) -> vectorPairDouble
        """
        _piranha.vectorPairDouble_swiginit(self, _piranha.new_vectorPairDouble(*args))
    push_back = _swig_new_instance_method(_piranha.vectorPairDouble_push_back)
    front = _swig_new_instance_method(_piranha.vectorPairDouble_front)
    back = _swig_new_instance_method(_piranha.vectorPairDouble_back)
    assign = _swig_new_instance_method(_piranha.vectorPairDouble_assign)
    resize = _swig_new_instance_method(_piranha.vectorPairDouble_resize)
    insert = _swig_new_instance_method(_piranha.vectorPairDouble_insert)
    reserve = _swig_new_instance_method(_piranha.vectorPairDouble_reserve)
    capacity = _swig_new_instance_method(_piranha.vectorPairDouble_capacity)
    __swig_destroy__ = _piranha.delete_vectorPairDouble

# Register vectorPairDouble in _piranha:
_piranha.vectorPairDouble_swigregister(vectorPairDouble)

class vectorInt(object):
    r"""Proxy of C++ std::vector< int > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_piranha.vectorInt_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_piranha.vectorInt___nonzero__)
    __bool__ = _swig_new_instance_method(_piranha.vectorInt___bool__)
    __len__ = _swig_new_instance_method(_piranha.vectorInt___len__)
    __getslice__ = _swig_new_instance_method(_piranha.vectorInt___getslice__)
    __setslice__ = _swig_new_instance_method(_piranha.vectorInt___setslice__)
    __delslice__ = _swig_new_instance_method(_piranha.vectorInt___delslice__)
    __delitem__ = _swig_new_instance_method(_piranha.vectorInt___delitem__)
    __getitem__ = _swig_new_instance_method(_piranha.vectorInt___getitem__)
    __setitem__ = _swig_new_instance_method(_piranha.vectorInt___setitem__)
    pop = _swig_new_instance_method(_piranha.vectorInt_pop)
    append = _swig_new_instance_method(_piranha.vectorInt_append)
    empty = _swig_new_instance_method(_piranha.vectorInt_empty)
    size = _swig_new_instance_method(_piranha.vectorInt_size)
    swap = _swig_new_instance_method(_piranha.vectorInt_swap)
    begin = _swig_new_instance_method(_piranha.vectorInt_begin)
    end = _swig_new_instance_method(_piranha.vectorInt_end)
    rbegin = _swig_new_instance_method(_piranha.vectorInt_rbegin)
    rend = _swig_new_instance_method(_piranha.vectorInt_rend)
    clear = _swig_new_instance_method(_piranha.vectorInt_clear)
    get_allocator = _swig_new_instance_method(_piranha.vectorInt_get_allocator)
    pop_back = _swig_new_instance_method(_piranha.vectorInt_pop_back)
    erase = _swig_new_instance_method(_piranha.vectorInt_erase)

    def __init__(self, *args):
        r"""
        __init__(vectorInt self) -> vectorInt
        __init__(vectorInt self, vectorInt other) -> vectorInt
        __init__(vectorInt self, std::vector< int >::size_type size) -> vectorInt
        __init__(vectorInt self, std::vector< int >::size_type size, std::vector< int >::value_type const & value) -> vectorInt
        """
        _piranha.vectorInt_swiginit(self, _piranha.new_vectorInt(*args))
    push_back = _swig_new_instance_method(_piranha.vectorInt_push_back)
    front = _swig_new_instance_method(_piranha.vectorInt_front)
    back = _swig_new_instance_method(_piranha.vectorInt_back)
    assign = _swig_new_instance_method(_piranha.vectorInt_assign)
    resize = _swig_new_instance_method(_piranha.vectorInt_resize)
    insert = _swig_new_instance_method(_piranha.vectorInt_insert)
    reserve = _swig_new_instance_method(_piranha.vectorInt_reserve)
    capacity = _swig_new_instance_method(_piranha.vectorInt_capacity)
    __swig_destroy__ = _piranha.delete_vectorInt

# Register vectorInt in _piranha:
_piranha.vectorInt_swigregister(vectorInt)

VERBOSE = _piranha.VERBOSE

INFINITE_VERTEX_ID = _piranha.INFINITE_VERTEX_ID

DEFAULT_VORONOI_QUANTITY = _piranha.DEFAULT_VORONOI_QUANTITY

REMOVED_COINCIDENCE = _piranha.REMOVED_COINCIDENCE

phi_fix = _piranha.phi_fix
SubtractionType_Area = _piranha.SubtractionType_Area

SubtractionType_AreaTrackEMD = _piranha.SubtractionType_AreaTrackEMD

SubtractionType_EMD = _piranha.SubtractionType_EMD

RhoSubtractionMode_Additive = _piranha.RhoSubtractionMode_Additive

RhoSubtractionMode_Fractional = _piranha.RhoSubtractionMode_Fractional

RemovalResult_Success = _piranha.RemovalResult_Success

RemovalResult_Coincidence = _piranha.RemovalResult_Coincidence

class DynamicVoronoiBase(object):
    r"""Proxy of C++ fastjet::contrib::piranha::DynamicVoronoiBase class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _piranha.delete_DynamicVoronoiBase
    description = _swig_new_instance_method(_piranha.DynamicVoronoiBase_description)
    set_subtraction_type = _swig_new_instance_method(_piranha.DynamicVoronoiBase_set_subtraction_type)
    set_R = _swig_new_instance_method(_piranha.DynamicVoronoiBase_set_R)
    subtraction_type = _swig_new_instance_method(_piranha.DynamicVoronoiBase_subtraction_type)
    track_emds = _swig_new_instance_method(_piranha.DynamicVoronoiBase_track_emds)
    R = _swig_new_instance_method(_piranha.DynamicVoronoiBase_R)
    __call__ = _swig_new_instance_method(_piranha.DynamicVoronoiBase___call__)
    valid_point = _swig_new_instance_method(_piranha.DynamicVoronoiBase_valid_point)
    number_of_primary_delaunay_vertices = _swig_new_instance_method(_piranha.DynamicVoronoiBase_number_of_primary_delaunay_vertices)
    total_area = _swig_new_instance_method(_piranha.DynamicVoronoiBase_total_area)
    areas = _swig_new_instance_method(_piranha.DynamicVoronoiBase_areas)
    area = _swig_new_instance_method(_piranha.DynamicVoronoiBase_area)
    coincidences = _swig_new_instance_method(_piranha.DynamicVoronoiBase_coincidences)
    emd_density = _swig_new_instance_method(_piranha.DynamicVoronoiBase_emd_density)
    neighbors = _swig_new_instance_method(_piranha.DynamicVoronoiBase_neighbors)
    vertex_is_primary_and_active = _swig_new_instance_method(_piranha.DynamicVoronoiBase_vertex_is_primary_and_active)

# Register DynamicVoronoiBase in _piranha:
_piranha.DynamicVoronoiBase_swigregister(DynamicVoronoiBase)
cvar = _piranha.cvar
PI = cvar.PI
TWOPI = cvar.TWOPI

class DynamicVoronoiCylinder(DynamicVoronoiBase):
    r"""Proxy of C++ fastjet::contrib::piranha::DynamicVoronoiCylinder class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(DynamicVoronoiCylinder self) -> DynamicVoronoiCylinder
        __init__(DynamicVoronoiCylinder self, fastjet::contrib::piranha::SubtractionType subtype, double R, double xmin, double ymin, double xmax, double ymax) -> DynamicVoronoiCylinder
        """
        _piranha.DynamicVoronoiCylinder_swiginit(self, _piranha.new_DynamicVoronoiCylinder(*args))
    primary_region = _swig_new_instance_method(_piranha.DynamicVoronoiCylinder_primary_region)
    valid_point = _swig_new_instance_method(_piranha.DynamicVoronoiCylinder_valid_point)
    neighbors = _swig_new_instance_method(_piranha.DynamicVoronoiCylinder_neighbors)
    remove = _swig_new_instance_method(_piranha.DynamicVoronoiCylinder_remove)
    __swig_destroy__ = _piranha.delete_DynamicVoronoiCylinder

# Register DynamicVoronoiCylinder in _piranha:
_piranha.DynamicVoronoiCylinder_swigregister(DynamicVoronoiCylinder)

class DynamicVoronoiDisk(DynamicVoronoiBase):
    r"""Proxy of C++ fastjet::contrib::piranha::DynamicVoronoiDisk class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(DynamicVoronoiDisk self) -> DynamicVoronoiDisk
        __init__(DynamicVoronoiDisk self, fastjet::contrib::piranha::SubtractionType subtype, double R) -> DynamicVoronoiDisk
        """
        _piranha.DynamicVoronoiDisk_swiginit(self, _piranha.new_DynamicVoronoiDisk(*args))
    set_R = _swig_new_instance_method(_piranha.DynamicVoronoiDisk_set_R)
    set_center = _swig_new_instance_method(_piranha.DynamicVoronoiDisk_set_center)
    x0 = _swig_new_instance_method(_piranha.DynamicVoronoiDisk_x0)
    y0 = _swig_new_instance_method(_piranha.DynamicVoronoiDisk_y0)
    valid_point = _swig_new_instance_method(_piranha.DynamicVoronoiDisk_valid_point)
    remove = _swig_new_instance_method(_piranha.DynamicVoronoiDisk_remove)
    __swig_destroy__ = _piranha.delete_DynamicVoronoiDisk

# Register DynamicVoronoiDisk in _piranha:
_piranha.DynamicVoronoiDisk_swigregister(DynamicVoronoiDisk)

VERTEX_DEFAULT_IND = _piranha.VERTEX_DEFAULT_IND

class BackgroundEstimatorBase(object):
    r"""Proxy of C++ fastjet::contrib::piranha::BackgroundEstimatorBase class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    rescaling_class = _swig_new_instance_method(_piranha.BackgroundEstimatorBase_rescaling_class)
    rho = _swig_new_instance_method(_piranha.BackgroundEstimatorBase_rho)

    def __init__(self):
        r"""__init__(BackgroundEstimatorBase self) -> BackgroundEstimatorBase"""
        _piranha.BackgroundEstimatorBase_swiginit(self, _piranha.new_BackgroundEstimatorBase())
    __swig_destroy__ = _piranha.delete_BackgroundEstimatorBase

# Register BackgroundEstimatorBase in _piranha:
_piranha.BackgroundEstimatorBase_swigregister(BackgroundEstimatorBase)

class SubtractionHistory(object):
    r"""Proxy of C++ fastjet::contrib::piranha::SubtractionHistory class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(SubtractionHistory self) -> SubtractionHistory
        __init__(SubtractionHistory self, double zp, double ze, unsigned int nv, unsigned int nr) -> SubtractionHistory
        """
        _piranha.SubtractionHistory_swiginit(self, _piranha.new_SubtractionHistory(*args))
    areas = _swig_new_instance_method(_piranha.SubtractionHistory_areas)
    zpt = _swig_new_instance_method(_piranha.SubtractionHistory_zpt)
    zemd = _swig_new_instance_method(_piranha.SubtractionHistory_zemd)
    nvalid = _swig_new_instance_method(_piranha.SubtractionHistory_nvalid)
    emdtot = _swig_new_instance_method(_piranha.SubtractionHistory_emdtot)
    nremoved = _swig_new_instance_method(_piranha.SubtractionHistory_nremoved)
    __swig_destroy__ = _piranha.delete_SubtractionHistory

# Register SubtractionHistory in _piranha:
_piranha.SubtractionHistory_swigregister(SubtractionHistory)
piranha_epsilon = cvar.piranha_epsilon

class GhostGridBase(object):
    r"""Proxy of C++ fastjet::contrib::piranha::GhostGridBase class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(GhostGridBase self, double drap, double dphi) -> GhostGridBase
        __init__(GhostGridBase self, unsigned int nrap, unsigned int nphi) -> GhostGridBase
        """
        _piranha.GhostGridBase_swiginit(self, _piranha.new_GhostGridBase(*args))
    __swig_destroy__ = _piranha.delete_GhostGridBase
    description = _swig_new_instance_method(_piranha.GhostGridBase_description)
    drap = _swig_new_instance_method(_piranha.GhostGridBase_drap)
    dphi = _swig_new_instance_method(_piranha.GhostGridBase_dphi)
    nrap = _swig_new_instance_method(_piranha.GhostGridBase_nrap)
    nphi = _swig_new_instance_method(_piranha.GhostGridBase_nphi)
    points = _swig_new_instance_method(_piranha.GhostGridBase_points)
    ghosts = _swig_new_instance_method(_piranha.GhostGridBase_ghosts)
    nghosts = _swig_new_instance_method(_piranha.GhostGridBase_nghosts)

# Register GhostGridBase in _piranha:
_piranha.GhostGridBase_swigregister(GhostGridBase)

class GhostGridRectangle(GhostGridBase):
    r"""Proxy of C++ fastjet::contrib::piranha::GhostGridRectangle class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(GhostGridRectangle self, double abs_rap_max, double d) -> GhostGridRectangle
        __init__(GhostGridRectangle self, double abs_rap_max, unsigned int n) -> GhostGridRectangle
        __init__(GhostGridRectangle self, double rap_min, double rap_max, double drap, double dphi) -> GhostGridRectangle
        __init__(GhostGridRectangle self, double rap_min, double rap_max, unsigned int nrap, unsigned int nphi) -> GhostGridRectangle
        __init__(GhostGridRectangle self, double rap_min, double phi_min, double rap_max, double phi_max, double drap, double dphi) -> GhostGridRectangle
        __init__(GhostGridRectangle self, double rap_min, double phi_min, double rap_max, double phi_max, unsigned int nrap, unsigned int nphi) -> GhostGridRectangle
        """
        _piranha.GhostGridRectangle_swiginit(self, _piranha.new_GhostGridRectangle(*args))
    description = _swig_new_instance_method(_piranha.GhostGridRectangle_description)
    region = _swig_new_instance_method(_piranha.GhostGridRectangle_region)
    __repr__ = _swig_new_instance_method(_piranha.GhostGridRectangle___repr__)
    __swig_destroy__ = _piranha.delete_GhostGridRectangle

# Register GhostGridRectangle in _piranha:
_piranha.GhostGridRectangle_swigregister(GhostGridRectangle)

class GhostGridDisk(GhostGridBase):
    r"""Proxy of C++ fastjet::contrib::piranha::GhostGridDisk class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(GhostGridDisk self, double R, double d) -> GhostGridDisk
        __init__(GhostGridDisk self, double R, unsigned int n) -> GhostGridDisk
        __init__(GhostGridDisk self, double R, double drap, double dphi) -> GhostGridDisk
        __init__(GhostGridDisk self, double R, unsigned int nrap, unsigned int nphi) -> GhostGridDisk
        """
        _piranha.GhostGridDisk_swiginit(self, _piranha.new_GhostGridDisk(*args))
    description = _swig_new_instance_method(_piranha.GhostGridDisk_description)
    R = _swig_new_instance_method(_piranha.GhostGridDisk_R)
    __repr__ = _swig_new_instance_method(_piranha.GhostGridDisk___repr__)
    __swig_destroy__ = _piranha.delete_GhostGridDisk

# Register GhostGridDisk in _piranha:
_piranha.GhostGridDisk_swigregister(GhostGridDisk)

INVALID_TOTAL_WEIGHT = _piranha.INVALID_TOTAL_WEIGHT

class IteratedVoronoiSubtractorDiskBase(object):
    r"""Proxy of C++ fastjet::contrib::piranha::IteratedVoronoiSubtractorBase< fastjet::contrib::piranha::DynamicVoronoiDisk > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(IteratedVoronoiSubtractorDiskBase self) -> IteratedVoronoiSubtractorDiskBase"""
        _piranha.IteratedVoronoiSubtractorDiskBase_swiginit(self, _piranha.new_IteratedVoronoiSubtractorDiskBase())
    __swig_destroy__ = _piranha.delete_IteratedVoronoiSubtractorDiskBase
    description = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_description)
    set_z = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_set_z)
    set_zpt = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_set_zpt)
    set_zemd = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_set_zemd)
    set_background_estimator = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_set_background_estimator)
    set_rho_subtraction_mode = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_set_rho_subtraction_mode)
    set_jet_constituents_use_same_rho = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_set_jet_constituents_use_same_rho)
    set_subtraction_type = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_set_subtraction_type)
    set_R = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_set_R)
    set_allow_repeats = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_set_allow_repeats)
    set_store_history = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_set_store_history)
    zpt = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_zpt)
    zemd = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_zemd)
    background_estimator = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_background_estimator)
    jet_constituents_use_same_rho = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_jet_constituents_use_same_rho)
    rho_subtraction_mode = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_rho_subtraction_mode)
    track_emds = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_track_emds)
    total_area = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_total_area)
    subtraction_type = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_subtraction_type)
    R = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_R)
    allow_repeats = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_allow_repeats)
    store_history = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_store_history)
    vor = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_vor)
    reapply = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_reapply)
    emd = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_emd)
    nvalid = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_nvalid)
    nremoved = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_nremoved)
    history = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_history)
    hist_size = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_hist_size)
    hist_i_areas_size = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDiskBase_hist_i_areas_size)

# Register IteratedVoronoiSubtractorDiskBase in _piranha:
_piranha.IteratedVoronoiSubtractorDiskBase_swigregister(IteratedVoronoiSubtractorDiskBase)

class IteratedVoronoiSubtractorCylinderBase(object):
    r"""Proxy of C++ fastjet::contrib::piranha::IteratedVoronoiSubtractorBase< fastjet::contrib::piranha::DynamicVoronoiCylinder > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(IteratedVoronoiSubtractorCylinderBase self) -> IteratedVoronoiSubtractorCylinderBase"""
        _piranha.IteratedVoronoiSubtractorCylinderBase_swiginit(self, _piranha.new_IteratedVoronoiSubtractorCylinderBase())
    __swig_destroy__ = _piranha.delete_IteratedVoronoiSubtractorCylinderBase
    description = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_description)
    set_z = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_set_z)
    set_zpt = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_set_zpt)
    set_zemd = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_set_zemd)
    set_background_estimator = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_set_background_estimator)
    set_rho_subtraction_mode = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_set_rho_subtraction_mode)
    set_jet_constituents_use_same_rho = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_set_jet_constituents_use_same_rho)
    set_subtraction_type = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_set_subtraction_type)
    set_R = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_set_R)
    set_allow_repeats = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_set_allow_repeats)
    set_store_history = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_set_store_history)
    zpt = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_zpt)
    zemd = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_zemd)
    background_estimator = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_background_estimator)
    jet_constituents_use_same_rho = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_jet_constituents_use_same_rho)
    rho_subtraction_mode = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_rho_subtraction_mode)
    track_emds = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_track_emds)
    total_area = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_total_area)
    subtraction_type = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_subtraction_type)
    R = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_R)
    allow_repeats = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_allow_repeats)
    store_history = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_store_history)
    vor = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_vor)
    reapply = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_reapply)
    emd = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_emd)
    nvalid = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_nvalid)
    nremoved = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_nremoved)
    history = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_history)
    hist_size = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_hist_size)
    hist_i_areas_size = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinderBase_hist_i_areas_size)

# Register IteratedVoronoiSubtractorCylinderBase in _piranha:
_piranha.IteratedVoronoiSubtractorCylinderBase_swigregister(IteratedVoronoiSubtractorCylinderBase)

class OptimalTransportSubtractorTransverseMomentumDeltaR(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::TransverseMomentum,fastjet::contrib::eventgeometry::DeltaR > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorTransverseMomentumDeltaR self, double z, EMDTransverseMomentumDeltaR emd, GhostGridDisk grid) -> OptimalTransportSubtractorTransverseMomentumDeltaR
        __init__(OptimalTransportSubtractorTransverseMomentumDeltaR self, double z, EMDTransverseMomentumDeltaR emd, GhostGridRectangle grid) -> OptimalTransportSubtractorTransverseMomentumDeltaR
        """
        _piranha.OptimalTransportSubtractorTransverseMomentumDeltaR_swiginit(self, _piranha.new_OptimalTransportSubtractorTransverseMomentumDeltaR(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumDeltaR_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumDeltaR_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumDeltaR_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumDeltaR_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumDeltaR_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumDeltaR___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumDeltaR___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorTransverseMomentumDeltaR

# Register OptimalTransportSubtractorTransverseMomentumDeltaR in _piranha:
_piranha.OptimalTransportSubtractorTransverseMomentumDeltaR_swigregister(OptimalTransportSubtractorTransverseMomentumDeltaR)

class OptimalTransportSubtractorTransverseMomentumHadronicDot(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::TransverseMomentum,fastjet::contrib::eventgeometry::HadronicDot > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorTransverseMomentumHadronicDot self, double z, EMDTransverseMomentumHadronicDot emd, GhostGridDisk grid) -> OptimalTransportSubtractorTransverseMomentumHadronicDot
        __init__(OptimalTransportSubtractorTransverseMomentumHadronicDot self, double z, EMDTransverseMomentumHadronicDot emd, GhostGridRectangle grid) -> OptimalTransportSubtractorTransverseMomentumHadronicDot
        """
        _piranha.OptimalTransportSubtractorTransverseMomentumHadronicDot_swiginit(self, _piranha.new_OptimalTransportSubtractorTransverseMomentumHadronicDot(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDot_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDot_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDot_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDot_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDot_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDot___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDot___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorTransverseMomentumHadronicDot

# Register OptimalTransportSubtractorTransverseMomentumHadronicDot in _piranha:
_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDot_swigregister(OptimalTransportSubtractorTransverseMomentumHadronicDot)

class OptimalTransportSubtractorTransverseMomentumHadronicDotMassive(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::TransverseMomentum,fastjet::contrib::eventgeometry::HadronicDotMassive > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorTransverseMomentumHadronicDotMassive self, double z, EMDTransverseMomentumHadronicDotMassive emd, GhostGridDisk grid) -> OptimalTransportSubtractorTransverseMomentumHadronicDotMassive
        __init__(OptimalTransportSubtractorTransverseMomentumHadronicDotMassive self, double z, EMDTransverseMomentumHadronicDotMassive emd, GhostGridRectangle grid) -> OptimalTransportSubtractorTransverseMomentumHadronicDotMassive
        """
        _piranha.OptimalTransportSubtractorTransverseMomentumHadronicDotMassive_swiginit(self, _piranha.new_OptimalTransportSubtractorTransverseMomentumHadronicDotMassive(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDotMassive_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDotMassive_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDotMassive_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDotMassive_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDotMassive_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDotMassive___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDotMassive___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorTransverseMomentumHadronicDotMassive

# Register OptimalTransportSubtractorTransverseMomentumHadronicDotMassive in _piranha:
_piranha.OptimalTransportSubtractorTransverseMomentumHadronicDotMassive_swigregister(OptimalTransportSubtractorTransverseMomentumHadronicDotMassive)

class OptimalTransportSubtractorTransverseEnergyDeltaR(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::TransverseEnergy,fastjet::contrib::eventgeometry::DeltaR > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorTransverseEnergyDeltaR self, double z, EMDTransverseEnergyDeltaR emd, GhostGridDisk grid) -> OptimalTransportSubtractorTransverseEnergyDeltaR
        __init__(OptimalTransportSubtractorTransverseEnergyDeltaR self, double z, EMDTransverseEnergyDeltaR emd, GhostGridRectangle grid) -> OptimalTransportSubtractorTransverseEnergyDeltaR
        """
        _piranha.OptimalTransportSubtractorTransverseEnergyDeltaR_swiginit(self, _piranha.new_OptimalTransportSubtractorTransverseEnergyDeltaR(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyDeltaR_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyDeltaR_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyDeltaR_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyDeltaR_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyDeltaR_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyDeltaR___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyDeltaR___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorTransverseEnergyDeltaR

# Register OptimalTransportSubtractorTransverseEnergyDeltaR in _piranha:
_piranha.OptimalTransportSubtractorTransverseEnergyDeltaR_swigregister(OptimalTransportSubtractorTransverseEnergyDeltaR)

class OptimalTransportSubtractorTransverseEnergyHadronicDot(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::TransverseEnergy,fastjet::contrib::eventgeometry::HadronicDot > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorTransverseEnergyHadronicDot self, double z, EMDTransverseEnergyHadronicDot emd, GhostGridDisk grid) -> OptimalTransportSubtractorTransverseEnergyHadronicDot
        __init__(OptimalTransportSubtractorTransverseEnergyHadronicDot self, double z, EMDTransverseEnergyHadronicDot emd, GhostGridRectangle grid) -> OptimalTransportSubtractorTransverseEnergyHadronicDot
        """
        _piranha.OptimalTransportSubtractorTransverseEnergyHadronicDot_swiginit(self, _piranha.new_OptimalTransportSubtractorTransverseEnergyHadronicDot(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDot_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDot_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDot_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDot_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDot_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDot___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDot___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorTransverseEnergyHadronicDot

# Register OptimalTransportSubtractorTransverseEnergyHadronicDot in _piranha:
_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDot_swigregister(OptimalTransportSubtractorTransverseEnergyHadronicDot)

class OptimalTransportSubtractorTransverseEnergyHadronicDotMassive(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::TransverseEnergy,fastjet::contrib::eventgeometry::HadronicDotMassive > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorTransverseEnergyHadronicDotMassive self, double z, EMDTransverseEnergyHadronicDotMassive emd, GhostGridDisk grid) -> OptimalTransportSubtractorTransverseEnergyHadronicDotMassive
        __init__(OptimalTransportSubtractorTransverseEnergyHadronicDotMassive self, double z, EMDTransverseEnergyHadronicDotMassive emd, GhostGridRectangle grid) -> OptimalTransportSubtractorTransverseEnergyHadronicDotMassive
        """
        _piranha.OptimalTransportSubtractorTransverseEnergyHadronicDotMassive_swiginit(self, _piranha.new_OptimalTransportSubtractorTransverseEnergyHadronicDotMassive(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDotMassive_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDotMassive_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDotMassive_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDotMassive_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDotMassive_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDotMassive___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDotMassive___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorTransverseEnergyHadronicDotMassive

# Register OptimalTransportSubtractorTransverseEnergyHadronicDotMassive in _piranha:
_piranha.OptimalTransportSubtractorTransverseEnergyHadronicDotMassive_swigregister(OptimalTransportSubtractorTransverseEnergyHadronicDotMassive)

class OptimalTransportSubtractorMomentumEEDot(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::Momentum,fastjet::contrib::eventgeometry::EEDot > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorMomentumEEDot self, double z, EMDMomentumEEDot emd, GhostGridDisk grid) -> OptimalTransportSubtractorMomentumEEDot
        __init__(OptimalTransportSubtractorMomentumEEDot self, double z, EMDMomentumEEDot emd, GhostGridRectangle grid) -> OptimalTransportSubtractorMomentumEEDot
        """
        _piranha.OptimalTransportSubtractorMomentumEEDot_swiginit(self, _piranha.new_OptimalTransportSubtractorMomentumEEDot(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDot_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDot_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDot_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDot_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDot_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDot___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDot___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorMomentumEEDot

# Register OptimalTransportSubtractorMomentumEEDot in _piranha:
_piranha.OptimalTransportSubtractorMomentumEEDot_swigregister(OptimalTransportSubtractorMomentumEEDot)

class OptimalTransportSubtractorMomentumEEDotMassive(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::Momentum,fastjet::contrib::eventgeometry::EEDotMassive > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorMomentumEEDotMassive self, double z, EMDMomentumEEDotMassive emd, GhostGridDisk grid) -> OptimalTransportSubtractorMomentumEEDotMassive
        __init__(OptimalTransportSubtractorMomentumEEDotMassive self, double z, EMDMomentumEEDotMassive emd, GhostGridRectangle grid) -> OptimalTransportSubtractorMomentumEEDotMassive
        """
        _piranha.OptimalTransportSubtractorMomentumEEDotMassive_swiginit(self, _piranha.new_OptimalTransportSubtractorMomentumEEDotMassive(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDotMassive_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDotMassive_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDotMassive_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDotMassive_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDotMassive_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDotMassive___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEDotMassive___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorMomentumEEDotMassive

# Register OptimalTransportSubtractorMomentumEEDotMassive in _piranha:
_piranha.OptimalTransportSubtractorMomentumEEDotMassive_swigregister(OptimalTransportSubtractorMomentumEEDotMassive)

class OptimalTransportSubtractorMomentumEEArcLength(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::Momentum,fastjet::contrib::eventgeometry::EEArcLength > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorMomentumEEArcLength self, double z, EMDMomentumEEArcLength emd, GhostGridDisk grid) -> OptimalTransportSubtractorMomentumEEArcLength
        __init__(OptimalTransportSubtractorMomentumEEArcLength self, double z, EMDMomentumEEArcLength emd, GhostGridRectangle grid) -> OptimalTransportSubtractorMomentumEEArcLength
        """
        _piranha.OptimalTransportSubtractorMomentumEEArcLength_swiginit(self, _piranha.new_OptimalTransportSubtractorMomentumEEArcLength(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLength_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLength_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLength_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLength_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLength_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLength___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLength___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorMomentumEEArcLength

# Register OptimalTransportSubtractorMomentumEEArcLength in _piranha:
_piranha.OptimalTransportSubtractorMomentumEEArcLength_swigregister(OptimalTransportSubtractorMomentumEEArcLength)

class OptimalTransportSubtractorMomentumEEArcLengthMassive(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::Momentum,fastjet::contrib::eventgeometry::EEArcLengthMassive > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorMomentumEEArcLengthMassive self, double z, EMDMomentumEEArcLengthMassive emd, GhostGridDisk grid) -> OptimalTransportSubtractorMomentumEEArcLengthMassive
        __init__(OptimalTransportSubtractorMomentumEEArcLengthMassive self, double z, EMDMomentumEEArcLengthMassive emd, GhostGridRectangle grid) -> OptimalTransportSubtractorMomentumEEArcLengthMassive
        """
        _piranha.OptimalTransportSubtractorMomentumEEArcLengthMassive_swiginit(self, _piranha.new_OptimalTransportSubtractorMomentumEEArcLengthMassive(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLengthMassive_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLengthMassive_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLengthMassive_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLengthMassive_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLengthMassive_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLengthMassive___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorMomentumEEArcLengthMassive___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorMomentumEEArcLengthMassive

# Register OptimalTransportSubtractorMomentumEEArcLengthMassive in _piranha:
_piranha.OptimalTransportSubtractorMomentumEEArcLengthMassive_swigregister(OptimalTransportSubtractorMomentumEEArcLengthMassive)

class OptimalTransportSubtractorEnergyEEDot(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::Energy,fastjet::contrib::eventgeometry::EEDot > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorEnergyEEDot self, double z, EMDEnergyEEDot emd, GhostGridDisk grid) -> OptimalTransportSubtractorEnergyEEDot
        __init__(OptimalTransportSubtractorEnergyEEDot self, double z, EMDEnergyEEDot emd, GhostGridRectangle grid) -> OptimalTransportSubtractorEnergyEEDot
        """
        _piranha.OptimalTransportSubtractorEnergyEEDot_swiginit(self, _piranha.new_OptimalTransportSubtractorEnergyEEDot(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDot_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDot_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDot_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDot_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDot_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDot___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDot___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorEnergyEEDot

# Register OptimalTransportSubtractorEnergyEEDot in _piranha:
_piranha.OptimalTransportSubtractorEnergyEEDot_swigregister(OptimalTransportSubtractorEnergyEEDot)

class OptimalTransportSubtractorEnergyEEDotMassive(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::Energy,fastjet::contrib::eventgeometry::EEDotMassive > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorEnergyEEDotMassive self, double z, EMDEnergyEEDotMassive emd, GhostGridDisk grid) -> OptimalTransportSubtractorEnergyEEDotMassive
        __init__(OptimalTransportSubtractorEnergyEEDotMassive self, double z, EMDEnergyEEDotMassive emd, GhostGridRectangle grid) -> OptimalTransportSubtractorEnergyEEDotMassive
        """
        _piranha.OptimalTransportSubtractorEnergyEEDotMassive_swiginit(self, _piranha.new_OptimalTransportSubtractorEnergyEEDotMassive(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDotMassive_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDotMassive_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDotMassive_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDotMassive_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDotMassive_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDotMassive___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEDotMassive___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorEnergyEEDotMassive

# Register OptimalTransportSubtractorEnergyEEDotMassive in _piranha:
_piranha.OptimalTransportSubtractorEnergyEEDotMassive_swigregister(OptimalTransportSubtractorEnergyEEDotMassive)

class OptimalTransportSubtractorEnergyEEArcLength(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::Energy,fastjet::contrib::eventgeometry::EEArcLength > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorEnergyEEArcLength self, double z, EMDEnergyEEArcLength emd, GhostGridDisk grid) -> OptimalTransportSubtractorEnergyEEArcLength
        __init__(OptimalTransportSubtractorEnergyEEArcLength self, double z, EMDEnergyEEArcLength emd, GhostGridRectangle grid) -> OptimalTransportSubtractorEnergyEEArcLength
        """
        _piranha.OptimalTransportSubtractorEnergyEEArcLength_swiginit(self, _piranha.new_OptimalTransportSubtractorEnergyEEArcLength(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLength_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLength_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLength_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLength_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLength_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLength___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLength___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorEnergyEEArcLength

# Register OptimalTransportSubtractorEnergyEEArcLength in _piranha:
_piranha.OptimalTransportSubtractorEnergyEEArcLength_swigregister(OptimalTransportSubtractorEnergyEEArcLength)

class OptimalTransportSubtractorEnergyEEArcLengthMassive(object):
    r"""Proxy of C++ fastjet::contrib::piranha::OptimalTransportSubtractor< fastjet::contrib::eventgeometry::EMD< double,fastjet::contrib::eventgeometry::Energy,fastjet::contrib::eventgeometry::EEArcLengthMassive > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(OptimalTransportSubtractorEnergyEEArcLengthMassive self, double z, EMDEnergyEEArcLengthMassive emd, GhostGridDisk grid) -> OptimalTransportSubtractorEnergyEEArcLengthMassive
        __init__(OptimalTransportSubtractorEnergyEEArcLengthMassive self, double z, EMDEnergyEEArcLengthMassive emd, GhostGridRectangle grid) -> OptimalTransportSubtractorEnergyEEArcLengthMassive
        """
        _piranha.OptimalTransportSubtractorEnergyEEArcLengthMassive_swiginit(self, _piranha.new_OptimalTransportSubtractorEnergyEEArcLengthMassive(*args))
    description = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLengthMassive_description)
    emd_obj = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLengthMassive_emd_obj)
    ghost_grid = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLengthMassive_ghost_grid)
    z = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLengthMassive_z)
    total_subtracted = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLengthMassive_total_subtracted)
    __call__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLengthMassive___call__)
    __repr__ = _swig_new_instance_method(_piranha.OptimalTransportSubtractorEnergyEEArcLengthMassive___repr__)
    __swig_destroy__ = _piranha.delete_OptimalTransportSubtractorEnergyEEArcLengthMassive

# Register OptimalTransportSubtractorEnergyEEArcLengthMassive in _piranha:
_piranha.OptimalTransportSubtractorEnergyEEArcLengthMassive_swigregister(OptimalTransportSubtractorEnergyEEArcLengthMassive)

class IteratedVoronoiSubtractorCylinder(IteratedVoronoiSubtractorCylinderBase):
    r"""Proxy of C++ fastjet::contrib::piranha::IteratedVoronoiSubtractorCylinder class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        r"""
        __init__(IteratedVoronoiSubtractorCylinder self, double abs_rap_max, fastjet::contrib::piranha::SubtractionType subtype=Area, double R=1.0, bool allow_repeats=False, bool store_history=False) -> IteratedVoronoiSubtractorCylinder
        __init__(IteratedVoronoiSubtractorCylinder self, double rap_min, double phi_min, double rap_max, double phi_max, fastjet::contrib::piranha::SubtractionType subtype=Area, double R=1.0, bool allow_repeats=False, bool store_history=False) -> IteratedVoronoiSubtractorCylinder
        """
        _piranha.IteratedVoronoiSubtractorCylinder_swiginit(self, _piranha.new_IteratedVoronoiSubtractorCylinder(*args))
    __call__ = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinder___call__)
    __repr__ = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorCylinder___repr__)
    __swig_destroy__ = _piranha.delete_IteratedVoronoiSubtractorCylinder

# Register IteratedVoronoiSubtractorCylinder in _piranha:
_piranha.IteratedVoronoiSubtractorCylinder_swigregister(IteratedVoronoiSubtractorCylinder)

class IteratedVoronoiSubtractorDisk(IteratedVoronoiSubtractorDiskBase):
    r"""Proxy of C++ fastjet::contrib::piranha::IteratedVoronoiSubtractorDisk class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        r"""__init__(IteratedVoronoiSubtractorDisk self, double R, fastjet::contrib::piranha::SubtractionType subtype=Area, bool allow_repeats=False, bool store_history=False, bool ensure_consistent_phi=True) -> IteratedVoronoiSubtractorDisk"""
        _piranha.IteratedVoronoiSubtractorDisk_swiginit(self, _piranha.new_IteratedVoronoiSubtractorDisk(*args, **kwargs))
    __call__ = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDisk___call__)
    __repr__ = _swig_new_instance_method(_piranha.IteratedVoronoiSubtractorDisk___repr__)
    __swig_destroy__ = _piranha.delete_IteratedVoronoiSubtractorDisk

# Register IteratedVoronoiSubtractorDisk in _piranha:
_piranha.IteratedVoronoiSubtractorDisk_swigregister(IteratedVoronoiSubtractorDisk)

class RecursiveSafeSubtractorTransverseMomentum(object):
    r"""Proxy of C++ fastjet::contrib::piranha::RecursiveSafeSubtractor< fastjet::contrib::eventgeometry::TransverseMomentum< double > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        r"""__init__(RecursiveSafeSubtractorTransverseMomentum self, double z, double f=1, fastjet::JetAlgorithm jet_alg=cambridge_algorithm) -> RecursiveSafeSubtractorTransverseMomentum"""
        _piranha.RecursiveSafeSubtractorTransverseMomentum_swiginit(self, _piranha.new_RecursiveSafeSubtractorTransverseMomentum(*args, **kwargs))
    description = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseMomentum_description)
    default_z = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseMomentum_default_z)
    default_f = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseMomentum_default_f)
    jet_alg = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseMomentum_jet_alg)
    weight_sums = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseMomentum_weight_sums)
    total_weight = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseMomentum_total_weight)
    reclustered_jet = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseMomentum_reclustered_jet)
    __repr__ = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseMomentum___repr__)
    __call__ = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseMomentum___call__)
    apply = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseMomentum_apply)
    __swig_destroy__ = _piranha.delete_RecursiveSafeSubtractorTransverseMomentum

# Register RecursiveSafeSubtractorTransverseMomentum in _piranha:
_piranha.RecursiveSafeSubtractorTransverseMomentum_swigregister(RecursiveSafeSubtractorTransverseMomentum)

class RecursiveSafeSubtractorTransverseEnergy(object):
    r"""Proxy of C++ fastjet::contrib::piranha::RecursiveSafeSubtractor< fastjet::contrib::eventgeometry::TransverseEnergy< double > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        r"""__init__(RecursiveSafeSubtractorTransverseEnergy self, double z, double f=1, fastjet::JetAlgorithm jet_alg=cambridge_algorithm) -> RecursiveSafeSubtractorTransverseEnergy"""
        _piranha.RecursiveSafeSubtractorTransverseEnergy_swiginit(self, _piranha.new_RecursiveSafeSubtractorTransverseEnergy(*args, **kwargs))
    description = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseEnergy_description)
    default_z = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseEnergy_default_z)
    default_f = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseEnergy_default_f)
    jet_alg = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseEnergy_jet_alg)
    weight_sums = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseEnergy_weight_sums)
    total_weight = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseEnergy_total_weight)
    reclustered_jet = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseEnergy_reclustered_jet)
    __repr__ = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseEnergy___repr__)
    __call__ = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseEnergy___call__)
    apply = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorTransverseEnergy_apply)
    __swig_destroy__ = _piranha.delete_RecursiveSafeSubtractorTransverseEnergy

# Register RecursiveSafeSubtractorTransverseEnergy in _piranha:
_piranha.RecursiveSafeSubtractorTransverseEnergy_swigregister(RecursiveSafeSubtractorTransverseEnergy)

class RecursiveSafeSubtractorEnergy(object):
    r"""Proxy of C++ fastjet::contrib::piranha::RecursiveSafeSubtractor< fastjet::contrib::eventgeometry::Energy< double > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        r"""__init__(RecursiveSafeSubtractorEnergy self, double z, double f=1, fastjet::JetAlgorithm jet_alg=cambridge_algorithm) -> RecursiveSafeSubtractorEnergy"""
        _piranha.RecursiveSafeSubtractorEnergy_swiginit(self, _piranha.new_RecursiveSafeSubtractorEnergy(*args, **kwargs))
    description = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorEnergy_description)
    default_z = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorEnergy_default_z)
    default_f = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorEnergy_default_f)
    jet_alg = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorEnergy_jet_alg)
    weight_sums = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorEnergy_weight_sums)
    total_weight = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorEnergy_total_weight)
    reclustered_jet = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorEnergy_reclustered_jet)
    __repr__ = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorEnergy___repr__)
    __call__ = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorEnergy___call__)
    apply = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorEnergy_apply)
    __swig_destroy__ = _piranha.delete_RecursiveSafeSubtractorEnergy

# Register RecursiveSafeSubtractorEnergy in _piranha:
_piranha.RecursiveSafeSubtractorEnergy_swigregister(RecursiveSafeSubtractorEnergy)

class RecursiveSafeSubtractorMomentum(object):
    r"""Proxy of C++ fastjet::contrib::piranha::RecursiveSafeSubtractor< fastjet::contrib::eventgeometry::Momentum< double > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        r"""__init__(RecursiveSafeSubtractorMomentum self, double z, double f=1, fastjet::JetAlgorithm jet_alg=cambridge_algorithm) -> RecursiveSafeSubtractorMomentum"""
        _piranha.RecursiveSafeSubtractorMomentum_swiginit(self, _piranha.new_RecursiveSafeSubtractorMomentum(*args, **kwargs))
    description = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorMomentum_description)
    default_z = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorMomentum_default_z)
    default_f = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorMomentum_default_f)
    jet_alg = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorMomentum_jet_alg)
    weight_sums = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorMomentum_weight_sums)
    total_weight = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorMomentum_total_weight)
    reclustered_jet = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorMomentum_reclustered_jet)
    __repr__ = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorMomentum___repr__)
    __call__ = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorMomentum___call__)
    apply = _swig_new_instance_method(_piranha.RecursiveSafeSubtractorMomentum_apply)
    __swig_destroy__ = _piranha.delete_RecursiveSafeSubtractorMomentum

# Register RecursiveSafeSubtractorMomentum in _piranha:
_piranha.RecursiveSafeSubtractorMomentum_swigregister(RecursiveSafeSubtractorMomentum)



def OptimalTransportSubtractor(*args, weight='TransverseMomentum', pairwise_distance='DeltaR', **kwargs):

    if weight == 'TransverseMomentum':
        if pairwise_distance == 'DeltaR':
            return OptimalTransportSubtractorTransverseMomentumDeltaR(*args, **kwargs)
        elif pairwise_distance == 'HadronicDot':
            return OptimalTransportSubtractorTransverseMomentumHadronicDot(*args, **kwargs)
        elif pairwise_distance == 'HadronicDotMassive':
            return OptimalTransportSubtractorTransverseMomentumHadronicDotMassive(*args, **kwargs)
        else:
            raise TypeError('pairwise distance `{}` not recognized'.format(pairwise_distance))

    elif weight == 'TransverseEnergy':
        if pairwise_distance == 'DeltaR':
            return OptimalTransportSubtractorTransverseEnergyDeltaR(*args, **kwargs)
        elif pairwise_distance == 'HadronicDot':
            return OptimalTransportSubtractorTransverseEnergyHadronicDot(*args, **kwargs)
        elif pairwise_distance == 'HadronicDotMassive':
            return OptimalTransportSubtractorTransverseEnergyHadronicDotMassive(*args, **kwargs)
        else:
            raise TypeError('pairwise distance `{}` not recognized'.format(pairwise_distance))

    elif weight == 'Energy':
        if pairwise_distance == 'EEDot':
            return OptimalTransportSubtractorEnergyEEDot(*args, **kwargs)
        elif pairwise_distance == 'EEDotMassive':
            return OptimalTransportSubtractorEnergyEEDotMassive(*args, **kwargs)
        elif pairwise_distance == 'EEArcLength':
            return OptimalTransportSubtractorEnergyEEArcLength(*args, **kwargs)
        elif pairwise_distance == 'EEArcLengthMassive':
            return OptimalTransportSubtractorEnergyEEArcLengthMassive(*args, **kwargs)
        else:
            raise TypeError('pairwise distance `{}` not recognized'.format(pairwise_distance))

    elif weight == 'Momentum':
        if pairwise_distance == 'EEDot':
            return OptimalTransportSubtractorMomentumEEDot(*args, **kwargs)
        elif pairwise_distance == 'EEDotMassive':
            return OptimalTransportSubtractorMomentumEEDotMassive(*args, **kwargs)
        elif pairwise_distance == 'EEArcLength':
            return OptimalTransportSubtractorMomentumEEArcLength(*args, **kwargs)
        elif pairwise_distance == 'EEArcLengthMassive':
            return OptimalTransportSubtractorMomentumEEArcLengthMassive(*args, **kwargs)
        else:
            raise TypeError('pairwise distance `{}` not recognized'.format(pairwise_distance))

    else:
        raise TypeError('weight `{}` not recognized'.format(weight))

def RecursiveSafeSubtractor(*args, weight='TransverseMomentum', **kwargs):

    if weight == 'TransverseMomentum':
        return RecursiveSafeSubtractorTransverseMomentum(*args, **kwargs)
    elif weight == 'TransverseEnergy':
        return RecursiveSafeSubtractorTransverseEnergy(*args, **kwargs)
    elif weight == 'Energy':
        return RecursiveSafeSubtractorEnergy(*args, **kwargs)
    elif weight == 'Momentum':
        return RecursiveSafeSubtractorMomentum(*args, **kwargs)
    else:
        raise TypeError('weight `{}` not recognized'.format(weight))




