name: Build and upload Python wheels

on:
  push:
    branches:
      - main

env:
  PYPI: 0
  PYPITEST: 1
  CIBW_SKIP: pp* *i686
  CIBW_BEFORE_ALL_LINUX: make shared
  CIBW_MANYLINUX_X86_64_IMAGE: ghcr.io/pkomiske/piranha_manylinux2010_x86_64:latest
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  TWINE_USERNAME: __token__
  TWINE_PASSWORD_PYPITEST: ${{ secrets.TWINE_PASSWORD_PYPITEST }}
  TWINE_PASSWORD_PYPI: ${{ secrets.TWINE_PASSWORD_PYPI }}

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Build wheels and upload to PyPI
        run: ./scripts/build-wheels-and-upload.sh sdist

  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install libomp
        run: brew install libomp
      - name: Compile Piranha library
        run: make shared
      - name: Build wheels and upload to PyPI
        run: ./scripts/build-wheels-and-upload.sh
